version: '3.7'

services:
  webhook:
    build: .
    ports:
      - "80:80"
      - "9000:9000"
    volumes:
      - /var/www/html
    environment:
      - GIT_REPO=https://github.com/Michi-Meierdiecks/auto-deploy-website.git
