
#### docker-compose.yml
```yaml
version: '3.8'

services:
  webhookd:
    build: .
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./webhooks:/home/ubuntu/webhooks
    container_name: webhookd-deploy
